apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: motionless-mastodon-java-springboot 
  janus-idp.io/tekton: motionless-mastodon-java-springboot
  backstage.io/kubernetes-id: motionless-mastodon-java-springboot
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: motionless-mastodon-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  